version: '1'

services:
  backend:
    env_file:
        "./backend/backend.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "ex/app-backend"
    ports:
      - ${backendPort}:${backendPort}
    envFrom:
    - configMapRef:
        name: app-configmap
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "ex/app-frontend"
    ports:
      - ${frontedPort}:${frontedPort}
    links:
      - "backend"
    volumes:
      - ./backend:/home/app
      - ./client:/home/client
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
